title: Bhargava Sai Kumar C # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Software Engineer
  <br><br>
  <a href="mailto:cbsaikumar@gmail.com">cbsaikumar@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/cbsaikumar/">LinkedIn Profile</a>
  <br>

theme: jekyll-theme-minimal
